version: 1.0.{build}
build_script:
- cmd: gradlew build
artifacts:
- path: .\build\libs\*
  name: files
deploy:
- provider: GitHub
  release: JWCore-v$(appveyor_build_version)
  auth_token:
    secure: S8dCcRphLSEBQEv8ZydU2D8pA707d9cMNIulWDrDb7WtKRHGNxMUkovpVLVybz8CkTO4miU1gH3leM9bodDhNxnuOI
    prerelease: true
cache:
  - C:\Users\Appveyor\.gradle -> appveyor.yml